spring:
  application:
    name: cards-api
  r2dbc:
    url: ${DATABASE_URL:r2dbc:mysql://127.0.0.1:3308/cards?allowPublicKeyRetrieval=true&useSSL=false&useLegacyDatetimeCode=false}
    name: ${DATABASE_NAME:cards}
    username: ${DATABASE_USER:user}
    password: ${DATABASE_PASSWORD:mauFJcuf5dhRMQrjj}
    pool:
      enabled: ${CONNECTION_POOL_ENABLED:true}
      initial-size: ${CONNECTION_POOL_INITIAL_SIZE:10}
      min-idle: ${MIN_POOL_SIZE:5}
      max-size: ${MAX_POOL_SIZE:20}
      validation-depth: ${VALIDATION_DEPTH:local}
      validation-query: ${VALIDATION_QUERY:SELECT 1}
      max-idle-time: ${MAX_IDLE_TIME:3m}
  liquibase:
    url: ${LIQUIBASE_DATABASE_URL:jdbc:mysql://127.0.0.1:3308/cards?allowPublicKeyRetrieval=true&useSSL=false&useLegacyDatetimeCode=false}
    user: ${DATABASE_USER:user}
    password: ${DATABASE_PASSWORD:mauFJcuf5dhRMQrjj}
    change-log: ${LIQUIBASE_CHANGELOG:db/changelog/db-changelog.yaml}
  sql:
    init:
      mode: always
      continue-on-error: false
logging:
  level:
    "com.logicea.cardsapi" : ${LOG_LEVEL:DEBUG}
    "liquibase" : info
  file:
    path: ${LOG_PATH:/tmp/cards/}
server:
  port: ${PORT:8080}
  undertow:
    buffer-size: 1024
    direct-buffers: true
    threads:
      io: 1000
      worker: 5000
management:
  endpoint:
    health:
      enabled: true
springfox:
  documentation:
    swagger-ui:
      enabled: true